#!/bin/bash
ulimit -s hard 
cd txl
make clean
make

INSTALL_DIR=.
LIBS=${INSTALL_DIR}/bin/
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-lang3-3.4/commons-lang3-3.4.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-exec-1.3/commons-exec-1.3.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-cli-1.3.1/commons-cli-1.3.1.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-io-2.4/commons-io-2.4.jar

cd ..

rm -rf bin/
mkdir bin/
find src/ -name "*.java" > sources
javac -d bin/ -cp $LIBS @sources
rm sources
