#!/bin/bash

# Clean
cd txl
make clean
cd ..
rm -rf bin/
mkdir bin

# Compile Java
find src/ -name "*.java" > sources.txt
javac -cp bin/:libs/commons-io-2.4/commons-io-2.4.jar -d bin/ @sources.txt

# Compile TXL
cd txl
make
cd ..
