#!/bin/bash

# Installation Directory
INSTALL_DIR=/home/jeff/Storage/git/ThriftyClone/

# Maximum Memory
TC_MEMORY=10G

# Build Classpath
LIBS=${INSTALL_DIR}/gbin/
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-lang3-3.4/commons-lang3-3.4.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-exec-1.3/commons-exec-1.3.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-cli-1.3.1/commons-cli-1.3.1.jar
LIBS=${LIBS}:${INSTALL_DIR}/libs/commons-io-2.4/commons-io-2.4.jar

# Run
time java -Xmx${TC_MEMORY} -cp ${LIBS} interfaces.CloneDetection $@ $INSTALL_DIR
