#!/bin/bash

# Installation Directory
TC_INSTALL_DIR=/home/jeff/Storage/git/ThriftyClone/

# Maximum Memory
TC_MEMORY=6G

cd ${TC_INSTALL_DIR}
java -Xmx${TC_MEMORY} -cp bin/:libs/commons-lang3-3.4/commons-lang3-3.4.jar:libs/commons-io-2.4/commons-io-2.4.jar:libs/commons-exec-1.3/commons-exec-1.3.jar:libs/commons-cli-1.3.1/commons-cli-1.3.1.jar interfaces.CloneDetection $@
