#!/bin/bash

### Standard Options
# $1 = mode
# $2 = install dir
# $3 = language
# $4 = granularity

### Parameters
# $5 = parameters

# Script
#script=${2}/txl/${3}-abstract-${4}s.txl
script=${2}/txl/${3}-abstract-alt-${4}s.x

if [ "$1" = "r" ]
then
	
	#txl stdin "${script}" - "${5}"
	#echo txl stdin "${script}" "${5}"
	./${script} stdin ${@:5}
	exit $?
fi

if [ "$1" = "v" ]
then
	if [ -e ${script} ]
	then
		exit 0
	else
		echo "Abstract does not exist for language ${3} and granularity ${4}."
		exit 1
	fi
fi

exit 1
