#!/bin/bash

### Standard Options
# $1 = mode
# $2 = install dir
# $3 = language
# $4 = granularity

### Parameters
# $5 = parameters


if [ "$1" = "r" ]
then
	cat /dev/stdin | java -jar $2/cfresources/ExtractCalls.jar $3	
	exit $?
fi

if [ "$1" = "v" ]
then
	if [ -e ${script} ]
	then
		exit 0
	else
		echo "Abstract does not exist for language ${3} and granularity ${4}."
		exit 1
	fi
fi

exit 1
