#!/bin/bash

### Standard Options
# $1 = mode
# $2 = install dir
# $3 = language
# $4 = granularity

### Parameters
# $5 = parameters

# Script
#script=${2}/txl/${3}-abstract-${4}s.txl
script=${2}/txl/${3}-abstract-${4}s.x

if [ "$1" = "r" ]
then
	java -cp bin/ cwbuild.cfprocessor.RetainUniqueLines 
	exit $?
fi

if [ "$1" = "v" ]
then
	exit 0
fi

exit 1
